Dr listing support
sinch/sinch-java-sms pull request #23
Opened 2022-04-28 15:26 UTC by zuzmaczek

2022-04-29 09:59 UTC, GSvensk requested changes
LGTM otherwise :+1:

2022-04-29 09:59 UTC, GSvensk commented on src/main/java/com/sinch/xms/DeliveryReportFilter.java
> +   * Limits results to batches having <em>any</em> the given tags.
incorrect java doc?

2022-04-29 12:45 UTC, zuzmaczek commented on src/main/java/com/sinch/xms/DeliveryReportFilter.java
> +   * Limits results to batches having <em>any</em> the given tags.
please rereview :)

2022-05-02 07:21 UTC, thomasf147 approved these changes

2022-05-02 07:28 UTC, thomasf147 commented
Perhaps increase the version number to 0.8.0

2022-05-02 08:43 UTC, zuzmaczek commented
> Perhaps increase the version number to 1.1.0

Maybe we should create PR for changing version to 1.0.0 and start doing proper changelogs? 
Anyone knows how that works? There are some old ones in some unfamiliar format

2022-05-03 08:20 UTC, merged