Mslres 5205
sinch/sinch-java-sms pull request #35
Opened 2023-06-21 13:17 UTC by thomasf147

2023-07-10 11:52 UTC, GSvensk requested changes

2023-07-10 11:52 UTC, GSvensk commented on src/main/java/com/sinch/xms/api/RecipientDeliveryReportSms.java
> +  public abstract Integer numberOfMessageParts();
Having to change to 
```
((RecipientDeliveryReportSms) deliveryReport).numberOfMessageParts()
```
is a BC break which can be avoided. Do we care? Did you plan to make this a major release anyway?

2023-07-10 12:14 UTC, thomasf147 commented on src/main/java/com/sinch/xms/api/BatchDeliveryReport.java
> -  public abstract static class Status {
It did not work with the abstract generating of of the impl with immutable and the fact that this is now a super class

2023-07-11 12:06 UTC, GSvensk commented on src/main/java/com/sinch/xms/api/BatchDeliveryReport.java
> -  public abstract static class Status {
alright 👍

2023-07-11 12:08 UTC, GSvensk approved these changes

2023-07-11 12:08 UTC, merged